backend:
  name: git-gateway

media_folder: "assets/uploads"      # where uploads live in your repo
public_folder: "/assets/uploads"    # how the site refers to them

# We'll plug text fields in later. For now this gives you a working /admin
# and a media library for images.
collections:
  - name: "media"
    label: "Media Library"
    files:
      - file: "assets/uploads/README.md"
        label: "Upload instructions"
        name: "uploads_readme"
        fields:
          - { label: "Note", name: "note", widget: "text", default: "Use the Media tab (top) to upload images. We will add editable page fields next." }
